"use strict";
const contactButton = document.querySelector("[data-save-contact]");
const toast = document.querySelector("#toast");
const languageToggle = document.querySelector("[data-language-toggle]");
const qrModal = document.querySelector("[data-qr-modal]");
const qrImage = document.querySelector("[data-qr-image]");
let toastTimer; let language = "ar";
function showToast(){ toast.classList.add("show"); clearTimeout(toastTimer); toastTimer=setTimeout(()=>toast.classList.remove("show"),3000); }
function saveContact(){ const vCard=["BEGIN:VCARD","VERSION:3.0","FN:Khaled Elgafarey","N:Elgafarey;Khaled;;;","TEL;TYPE=CELL:+201010474002","URL:https://mlthnrgev-cell.github.io/Eng-Khaled-Elgafarey-/index.html","URL;TYPE=Facebook:https://www.facebook.com/share/1C6KMp8SJZ/","URL;TYPE=Instagram:https://www.instagram.com/khaledelgafarey_","URL;TYPE=TikTok:https://www.tiktok.com/@khaledelgafarey0","NOTE:Electronics Student - Al-Suwaidi Technical Academy","END:VCARD"].join("\n"); const fileUrl=URL.createObjectURL(new Blob([vCard],{type:"text/vcard;charset=utf-8"})); const link=Object.assign(document.createElement("a"),{href:fileUrl,download:"Khaled-Elgafarey.vcf"}); document.body.append(link);link.click();link.remove();URL.revokeObjectURL(fileUrl);showToast(); }
function setLanguage(next){ language=next; document.documentElement.lang=language;document.documentElement.dir=language==="ar"?"rtl":"ltr";document.querySelectorAll("[data-ar][data-en]").forEach(el=>el.textContent=el.dataset[language]);languageToggle.textContent=language==="ar"?"EN":"ع";languageToggle.setAttribute("aria-label",language==="ar"?"Switch to English":"التبديل إلى العربية");document.title=language==="ar"?"خالد الجعفري | بطاقة تعريف رقمية":"Khaled Elgafarey | Digital Profile"; }
function openQr(){ const profileUrl="https://mlthnrgev-cell.github.io/Eng-Khaled-Elgafarey-/index.html";qrImage.src=`https://api.qrserver.com/v1/create-qr-code/?size=260x260&margin=12&data=${encodeURIComponent(profileUrl)}`;qrModal.classList.add("is-open");qrModal.setAttribute("aria-hidden","false"); }
function closeQr(){qrModal.classList.remove("is-open");qrModal.setAttribute("aria-hidden","true");}
contactButton?.addEventListener("click",saveContact);languageToggle?.addEventListener("click",()=>setLanguage(language==="ar"?"en":"ar"));document.querySelector("[data-qr-open]")?.addEventListener("click",openQr);document.querySelector("[data-qr-close]")?.addEventListener("click",closeQr);qrModal?.addEventListener("click",event=>{if(event.target===qrModal)closeQr();});document.addEventListener("keydown",event=>{if(event.key==="Escape")closeQr();});
